name: Alief Aditya Nugraha
pageTitle: Links
url: https://github.com/aliefadityanugraha
logo: static/img/aku.jpeg
favicon: https://www.freeiconspng.com/thumbs/world-icon-png/world-wide-web-icon-15.png
bio: Coder | Designer | Editor | Part of getownyour_self
